config/routes.rb
BackchannelApp::Application.routes.draw do
  resources :tags

  resources :categories

  resources :vote_replies

  resources :vote_posts

  resources :replies

  resources :posts

  resources :logins

  resources :users

end

app/models/vote_post.rb
class VotePost < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  attr_accessible :vote_post_count
end

app/controllers/vote_posts_controller.rb
class VotePostsController < ApplicationController
  # GET /vote_posts
  # GET /vote_posts.json
  def index
    @vote_posts = VotePost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vote_posts }
    end
  end

  # GET /vote_posts/1
  # GET /vote_posts/1.json
  def show
    @vote_post = VotePost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote_post }
    end
  end

  # GET /vote_posts/new
  # GET /vote_posts/new.json
  def new
    @vote_post = VotePost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote_post }
    end
  end

  # GET /vote_posts/1/edit
  def edit
    @vote_post = VotePost.find(params[:id])
  end

  # POST /vote_posts
  # POST /vote_posts.json
  def create
    @vote_post = VotePost.new(params[:vote_post])

    respond_to do |format|
      if @vote_post.save
        format.html { redirect_to @vote_post, notice: 'Vote post was successfully created.' }
        format.json { render json: @vote_post, status: :created, location: @vote_post }
      else
        format.html { render action: "new" }
        format.json { render json: @vote_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vote_posts/1
  # PUT /vote_posts/1.json
  def update
    @vote_post = VotePost.find(params[:id])

    respond_to do |format|
      if @vote_post.update_attributes(params[:vote_post])
        format.html { redirect_to @vote_post, notice: 'Vote post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vote_posts/1
  # DELETE /vote_posts/1.json
  def destroy
    @vote_post = VotePost.find(params[:id])
    @vote_post.destroy

    respond_to do |format|
      format.html { redirect_to vote_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vote_posts_helper.rb
module VotePostsHelper
end

app/views/vote_posts/_form.html.erb
<%= form_for(@vote_post) do |f| %>
  <% if @vote_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote_post.errors.count, "error") %> prohibited this vote_post from being saved:</h2>

      <ul>
      <% @vote_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vote_post_count %><br />
    <%= f.number_field :vote_post_count %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vote_posts/edit.html.erb
<h1>Editing vote_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote_post %> |
<%= link_to 'Back', vote_posts_path %>

app/views/vote_posts/index.html.erb
<h1>Listing vote_posts</h1>

<table>
  <tr>
    <th>Vote post count</th>
    <th>Post</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vote_posts.each do |vote_post| %>
  <tr>
    <td><%= vote_post.vote_post_count %></td>
    <td><%= vote_post.post %></td>
    <td><%= vote_post.user %></td>
    <td><%= link_to 'Show', vote_post %></td>
    <td><%= link_to 'Edit', edit_vote_post_path(vote_post) %></td>
    <td><%= link_to 'Destroy', vote_post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote post', new_vote_post_path %>

app/views/vote_posts/new.html.erb
<h1>New vote_post</h1>

<%= render 'form' %>

<%= link_to 'Back', vote_posts_path %>

app/views/vote_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vote post count:</b>
  <%= @vote_post.vote_post_count %>
</p>

<p>
  <b>Post:</b>
  <%= @vote_post.post %>
</p>

<p>
  <b>User:</b>
  <%= @vote_post.user %>
</p>


<%= link_to 'Edit', edit_vote_post_path(@vote_post) %> |
<%= link_to 'Back', vote_posts_path %>