config/routes.rb
BackchannelApp::Application.routes.draw do
  resources :tags

  resources :categories

  resources :vote_replies

  resources :vote_posts

  resources :replies

  resources :posts

  resources :logins

  resources :users

end

app/models/login.rb
class Login < ActiveRecord::Base
  belongs_to :user
  attr_accessible :pwd
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logins }
    end
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
    @login = Login.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @login }
    end
  end

  # GET /logins/new
  # GET /logins/new.json
  def new
    @login = Login.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @login }
    end
  end

  # GET /logins/1/edit
  def edit
    @login = Login.find(params[:id])
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(params[:login])

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render json: @login, status: :created, location: @login }
      else
        format.html { render action: "new" }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logins/1
  # PUT /logins/1.json
  def update
    @login = Login.find(params[:id])

    respond_to do |format|
      if @login.update_attributes(params[:login])
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login = Login.find(params[:id])
    @login.destroy

    respond_to do |format|
      format.html { redirect_to logins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pwd %><br />
    <%= f.text_field :pwd %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<h1>Listing logins</h1>

<table>
  <tr>
    <th>Pwd</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logins.each do |login| %>
  <tr>
    <td><%= login.pwd %></td>
    <td><%= login.user %></td>
    <td><%= link_to 'Show', login %></td>
    <td><%= link_to 'Edit', edit_login_path(login) %></td>
    <td><%= link_to 'Destroy', login, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pwd:</b>
  <%= @login.pwd %>
</p>

<p>
  <b>User:</b>
  <%= @login.user %>
</p>


<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>